---

- name: include setup tasks
  include: setup.yml
  tags: ["awstats:setup", "setup"]

- name: include installation tasks
  include: install.yml
  tags: ["awstats:install", "install"]

- name: include configuration tasks
  include: configure.yml
  tags: ["awstats:configure", "configure"]
